insert into equipment (name_he,name_en,category,quantity,details,active) values
('בוסו','BOSU Balance Trainer','balance',3,'',true),
('מדרגה','Step Platform','cardio',1,'',true),
('משקולות יד 1 ק״ג','1 kg Dumbbells','dumbbells',10,'10 יחידות',true),
('משקולות יד 1.5 ק״ג','1.5 kg Dumbbells','dumbbells',8,'8 יחידות',true),
('משקולות יד 2 ק״ג','2 kg Dumbbells','dumbbells',8,'8 יחידות',true),
('משקולות יד 3 ק״ג','3 kg Dumbbells','dumbbells',8,'8 יחידות',true),
('משקולות יד 4 ק״ג','4 kg Dumbbells','dumbbells',6,'6 יחידות',true),
('משקולות יד 5 ק״ג','5 kg Dumbbells','dumbbells',4,'4 יחידות',true),
('משקולות יד 6 ק״ג','6 kg Dumbbells','dumbbells',4,'4 יחידות',true),
('משקולות יד 7.5 ק״ג','7.5 kg Dumbbells','dumbbells',2,'2 יחידות',true),
('משקולות יד 10 ק״ג','10 kg Dumbbells','dumbbells',2,'2 יחידות',true),
('מוט משקולת + סט פלטות','Barbell + Plates Set','barbells',3,'כל סט עד 20 ק״ג',true),
('גומיות התנגדות','Resistance Bands','bands',12,'12 סטים',true),
('גומיות עם ידיות','Resistance Tubes with Handles','bands',12,'',true),
('גומיות ירכיים','Hip / Mini Bands','bands',10,'',true),
('קוביות פילאטיס','Pilates Blocks','pilates',28,'',true),
('מזרני פילאטיס','Pilates Mats','pilates',12,'',true),
('כדורי משקולת 1 ק״ג','1 kg Weighted Balls','balls',14,'',true),
('כדורי פיזיו','Swiss / Physio Balls','balls',5,'',true),
('אוברבול','Overball / Small Pilates Ball','balls',5,'',true),
('גלילי פילאטיס','Pilates / Foam Rollers','recovery',11,'',true),
('פיתה שיווי משקל','Balance Disc','balance',4,'',true),
('קטלבל 4–8 ק״ג','Kettlebells 4–8 kg','kettlebells',12,'הנחת V1: 4 יחידות בכל אחד מהמשקלים 4, 6, 8 ק״ג — יש לאשר',true);
