import {NextResponse} from "next/server";
import crypto from "crypto";
import seed from "../../../data/exercises.json";
import {supabaseAdmin} from "../../../lib/supabase";
const safeEqual=(a,b)=>{const A=Buffer.from(String(a||"")),B=Buffer.from(String(b||""));return A.length===B.length&&crypto.timingSafeEqual(A,B)};
const isAdmin=req=>Boolean(process.env.ADMIN_PIN)&&safeEqual(req.headers.get("x-admin-pin"),process.env.ADMIN_PIN);
const dbToExercise=x=>({id:x.exercise_id||x.id,he:x.he,en:x.en,region:x.region,muscles:x.muscles,equipment:x.equipment_name,level:x.level,cue:x.cue,pattern:x.pattern,goal:x.goal,regression:x.regression||"",progression:x.progression||"",safety:x.safety||"",videoUrl:x.video_url||"",imageUrl:x.image_url||"",antagonist_group:x.antagonist_group||"",source:x.source||"database",active:x.active!==false});
export async function GET(){const db=supabaseAdmin();if(!db)return NextResponse.json(seed);const{data,error}=await db.from("exercises").select("*").eq("active",true).order("created_at");if(error)return NextResponse.json(seed);const dynamic=(data||[]).map(dbToExercise),seen=new Set(dynamic.map(x=>x.id));return NextResponse.json([...seed.filter(x=>!seen.has(x.id)),...dynamic])}
export async function POST(req){if(!isAdmin(req))return NextResponse.json({error:"PIN שגוי"},{status:401});const db=supabaseAdmin();if(!db)return NextResponse.json({error:"Supabase עדיין לא מחובר"},{status:503});const b=await req.json();if(!b?.id||!b?.he||!b?.en)return NextResponse.json({error:"חסרים פרטי תרגיל"},{status:400});const row={exercise_id:b.id,he:b.he,en:b.en,region:b.region||"כל הגוף",muscles:b.muscles||"",equipment_name:b.equipment||"ללא ציוד",level:b.level||"בינוניים",cue:b.cue||"",pattern:b.pattern||"Strength",goal:b.goal||"חיזוק",regression:b.regression||"",progression:b.progression||"",safety:b.safety||"",video_url:b.videoUrl||"",image_url:b.imageUrl||"",antagonist_group:b.antagonist_group||"",source:b.source||"admin",active:b.active!==false};const{data,error}=await db.from("exercises").upsert(row,{onConflict:"exercise_id"}).select().single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json(dbToExercise(data))}
